version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: profissionais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: rafaelbrunof/simples-dental:latest
    container_name: profissionais-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: