spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/profissionais
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080